services:
    app:
        build:
            context: .
            network: host
        container_name: app
        ports:
            - "8000:8000"
        volumes:
            - ./volumes/logs_data:/logs
            - ./volumes/files_data:/files
        depends_on:
            - db

    migrate:
        build:
            context: .
            network: host
        command: sh -c "sleep 5 && alembic upgrade head"
        depends_on:
            - db

    db:
        image: postgres:17.5
        container_name: db
        restart: always
        environment:
            POSTGRES_USER: ${pg_user}
            POSTGRES_PASSWORD: ${pg_password}
            POSTGRES_DB: ${pg_database}
        volumes:
            - ./volumes/postgresql_data:/var/lib/postgresql/data

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
