version: "3.9"

services:
    web:
        build: .
        container_name: app
        ports:
            - "8000:8000"
        volumes:
            - ./volumes/logs_data:/logs
            - ./volumes/files_data:/files
        depends_on:
            - db
            - redis
            - rabbitmq

    migrate:
        build: .
        command: sh -c "sleep 20 && alembic upgrade head"
        depends_on:
            - rabbitmq
            - redis
            - db

    celery_worker:
        build: .
        container_name: celery_worker
        command: celery --app celery_app.app.celery_app worker --pool threads --loglevel INFO
        depends_on:
            - rabbitmq
            - redis
            - db

    db:
        image: postgres:17.5
        container_name: db
        restart: always
        environment:
            POSTGRES_USER: ${pg_user}
            POSTGRES_PASSWORD: ${pg_password}
            POSTGRES_DB: ${pg_database}
        ports:
            - "5432:5432"
        volumes:
            - ./volumes/postgresql_data:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD-SHELL', "pg_isready -U ${pg_user}"]
            interval: 60s
            timeout: 5s
            retries: 5

    redis:
        image: redis:8.0.2
        container_name: redis
        restart: always
        ports:
            - "6379:6379"
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 60s
            timeout: 5s
            retries: 5
        volumes:
            - ./volumes/redis_data:/data

    rabbitmq:
        image: rabbitmq:4.1.0-management
        container_name: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: ${rabbit_mq_username}
            RABBITMQ_DEFAULT_PASS: ${rabbit_mq_password}
        volumes:
            - ./volumes/rabbitmq_data:/var/lib/rabbitmq
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "rabbitmqctl status"]
            interval: 60s
            timeout: 5s
            retries: 5
    
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080