version: "3.9"

services:
    web:
        build: .
        container_name: app
        ports:
            - "8000:8000"
        volumes:
            - ./app:/code/app
        env_file:
            - .env-docker
        environment:
            - ENV_FILE=.env-docker
        depends_on:
            - db
            - redis
            - rabbitmq

    migrate:
        build: .
        command: alembic upgrade head
        volumes:
            - ./app:/code/app
        env_file:
            - .env-docker
        environment:
            - ENV_FILE=.env-docker
        depends_on:
            - rabbitmq
            - redis
            - db

    celery_worker:
        build: .
        container_name: celery_worker
        command: celery --app celery_app.app.celery_app worker --pool threads --loglevel INFO
        volumes:
            - ./app:/code/app
        env_file:
            - .env-docker
        environment:
            - ENV_FILE=.env-docker
        depends_on:
            - rabbitmq
            - redis
            - db

    db:
        image: postgres:latest
        container_name: db
        restart: always
        environment:
            POSTGRES_USER: ${PG_USER}
            POSTGRES_PASSWORD: ${PG_PASSWORD}
            POSTGRES_DB: ${PG_DATABASE}
        env_file:
            - .env-docker
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

    redis:
        image: redis:latest
        container_name: redis
        restart: always
        ports:
            - "6379:6379"

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: ${USER}
            RABBITMQ_DEFAULT_PASS: ${PASSWORD}
        env_file:
            - .env-docker
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        restart: unless-stopped


volumes:
    pgdata:
    rabbitmq_data: