[tool.poetry]
name = "fastapi-template"
version = "0.1.0"
description = ""
authors = ["umarr <umarr.developer@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.11.4"
alembic = "^1.15.2"
sqlalchemy = "^2.0.41"
asyncpg = "^0.30.0"
python-dotenv = "^1.1.0"
fastapi = "^0.115.12"
python-multipart = "^0.0.20"
bcrypt = "^4.3.0"
pyjwt = "^2.10.1"
mypy = "^1.15.0"
sqladmin = "^0.20.1"
uvicorn = "^0.34.2"
black = "^25.1.0"
hypercorn = "^0.17.3"
alembic-postgresql-enum = "^1.7.0"
aiofiles = "^24.1.0"
aiocache = "^0.12.3"
pydantic-settings = "^2.9.1"
pytest = "^8.3.5"
pytest-asyncio = "^1.0.0"
itsdangerous = "^2.2.0"
celery = "^5.5.3"
httpx = "^0.28.1"
uuid6 = "^2025.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
